name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: build the C# code
      run: |
        dotnet build
    - name: run the C# test
      run: |
        dotnet test
    - name: build the TypeScript code
      run: |
        cd DotnetTemplate.Web
        npm install
        npm run build
    - name: run the linter on the TypeScript code
      run: |
        cd DotnetTemplate.Web
        npm run lint
    - name: run the TypeScript tests
      run: |
        npm t